name: Create and Read CSV
on:
  push:
    branches: [ main ] # Cambia 'main' por el nombre de la rama que deseas utilizar.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create CSV
      run: |
        echo "Creating CSV..."
        echo "Name, Age" >> data.csv
        echo "John, 25" >> data.csv
        echo "Jane, 30" >> data.csv
    - name: Read CSV
      run: |
        echo "Reading CSV..."
        cat data.csv
